title: 'Gun powder '
description: Looking for gun powder close to me
template:
  repo: gun-powder-template
  name: gun-powder
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
